### PR TITLE
Japanese translation 1st (Revised edition)

### PR DESCRIPTION
**Pull request by youkung**
I corrected the pointed out part and translated everything except the part that I decided to be fine.
I checked the operation with Firefox69 of Windows10, Firefox69 of Debian Buster and Firefox69 of FreeBSD12p10, and confirmed that there was no problem in Japanese display.
Please use it if you like.
https://i.imgur.com/waZ6UZ4.png
https://i.imgur.com/xWJ7ksh.png

### CODE REVIEW

**Comment by nmaier** [comment]
I also invited you to the translators team where I intent to post updates for translators in the future, such as new features that require additional translations

**Comment by youkung** [comment]
Thank you for accepting my commit. I am very impressed!
That's a big story with the translator team. I do not know what is possible, but thank you in the future.
Finally, when will this change be reflected in the AMO add-on?

**Comment by nmaier** [comment]
I pushed a new version just now, it is awaiting moderation, so depending on how fast mozilla is, probably within the next day.

**Comment by nmaier** [comment]
Actually scratch that. Just as I wrote this I got the email that it is publish. So it is available already.

**Comment by youkung** [comment]
The update of the add-on was confirmed in my Firefox.
I would like to report to my friends.
Congratulations on your updates.
See you next time. goodbye.

**Pull request merged**
