### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by wsxy162**

### CODE REVIEW

**Comment by haiwx** [comment]
我上次遗留的问题以及修改意见：

_已重置过去所有**以前**记住的确认项！_    要删掉_**以前**_

不要显示通用右键菜单项    不要 改 不

**Comment by nmaier** [comment]
Wait, what is happening now?
I see both of you had a PR open and @haiwx closed theirs.

**Comment by haiwx** [comment]
@nmaier I didn't notice his PR, so I closed.

**Comment by haiwx** [comment]
@nmaier It's time to  **Merge**  😁

**Comment by nmaier** [comment]
OK then.
Thanks!

**Pull request merged**
