### PR TITLE
Update of zh_CN locale

### PR DESCRIPTION
**Pull request by haiwx**

### CODE REVIEW

**Comment by nmaier** [comment]
There seem to be some larger changes in there. And I know nothing about the language, so there is no way to judge the changes for me.

Adding @wsxy162, who made the initial translation, so you can maybe give some input here too?

@haiwx can you explain a little more what kind of changes you made?

**Comment by Riajyuu** [comment]
Checked through changes quickly just now and agreed. All are nothing more than grammar/wording refine.

**Comment by wsxy162** [comment]
I'm fine with most changes. Still there are some strings need to be reviewed.
1. "中文 (简体)", "超大 (> $HIGH$)" should use full-width brackets.
2. "queued" is translated as "已排队" or "已入队", which is better one? Previous one is about the downloading status, second one is describing the adding status.
3. "单词下载" has a typo.
4. "Check Selected Items" is untranslated, can be "勾选选中项/所选项".
5. "$ITEMS$ items selected..." Three dots as a ellipsis, is this on purpose? @nmaier
6. "Open File" should be translated as "打开文件" not "打开文件夹".
7. "Do not show general context menu items". Don't miss the word “general”, not all the menu will hide.

"Referrer" is translated into "来源/引用", "Archive" into "归档/存档/压缩包" and "Image" into "图像/图片", these are personal preferences.

**Comment by haiwx** [comment]
@nmaier I have fixed those, please have a look , Thx

**Comment by nmaier** [comment]
>"queued" is translated as "已排队" or "已入队", which is better one? Previous one is about the downloading status, second one is describing the adding status.

Cannot really help you there as I have no clue about the actual nuances. Just that it's about adding to the queue. The downloads added may not start immediately if the queue is already filled, but may have to wait their turn. So I am guessing the "已入队" that is in there now is more appropriate?

>"$ITEMS$ items selected..." Three dots as a ellipsis, is this on purpose? @nmaier

Yes, all 3 dots "..." in the translation are preferred to be the unicode ellipsis sign.

If there are no more objections, since @wsxy162 and @Riajyuu generally agreed that the changes are OK and the issues brought up seem to have been addressed, I will merge this within the next day.

**Comment by nmaier** [comment]
Alright then, applied.

**Pull request merged**
