### PR TITLE
Add zh_TW locale

### PR DESCRIPTION
**Pull request by sharkurl**
add message.json for zh-TW locale
append zh_TW line in all.json

### CODE REVIEW

**Comment by nmaier** [comment]
First of all, thanks for getting involved!

There is one untranslated string, namely `ask_again_later`.
Is this by design or did you accidentally miss it?

**Comment by sharkurl** [comment]
The string ask_again_later was not been updated as ask_again_later accidentally.
File revised, anything abnormal else?

**Comment by nmaier** [comment]
Well, the rest looks OK. Of course I cannot help you find typos or anything like that as I do not speak that language.

**Comment by nmaier** [comment]
Oh, and I'd suggest using the translate site in the future.

**Pull request merged**
